# This file is automatically generated.  Do not edit.

import ctypes
import yaml

import pack2
import py_types

class ParamSourceHeaderMagic(ctypes._SimpleCData, py_types.PackableCType):
  _type_ = 'l'
  _value_map = {
    1614891826: 'Magic',
  }
  _c_value_map = {
    1614891826: 'kParamSourceHeaderMagicMagic',

  }
  _name_map = {
    'Magic': 1614891826,
  }
  max_value = 1614891826
  min_value = 1614891826

  def __init__(self, value=0):
    super(self.__class__, self).__init__()
    self.__setstate__(value)

  def __setstate__(self, state):
    if isinstance(state, basestring):
      self.value = self._name_map[state]
    elif isinstance(state, self.__class__):
      self.value = state.value
    else:
      self.value = state

  def __repr__(self):
    return self._value_map[self.value]

  def __hash__(self):
    return self.value

  def __eq__(self, other):
    if isinstance(other, basestring):
      return self.value == self._name_map[other]
    elif isinstance(other, self.__class__):
      return self.value == other.value
    else:
      return self.value == other

  def __ne__(self, other):
    return not self.__eq__(other)

  def CName(self):
    return self._c_value_map[self.value]

  @classmethod
  def Names(cls):
    return [ParamSourceHeaderMagic(v) for v in cls._value_map.keys()]

  @classmethod
  def iteritems(cls):
    return cls._name_map.iteritems()

  @classmethod
  def HeaderFile(cls):
    return "avionics/firmware/params/param_source_header.h"

  @classmethod
  def TypeName(cls):
    return "ParamSourceHeaderMagic"

ParamSourceHeaderMagic.MAGIC = ParamSourceHeaderMagic(1614891826)

class ParamSourceEncoding(ctypes._SimpleCData, py_types.PackableCType):
  _type_ = 'l'
  _value_map = {
    0: 'Bzip2',
  }
  _c_value_map = {
    0: 'kParamSourceEncodingBzip2',

  }
  _name_map = {
    'Bzip2': 0,
  }
  max_value = 0
  min_value = 0

  def __init__(self, value=0):
    super(self.__class__, self).__init__()
    self.__setstate__(value)

  def __setstate__(self, state):
    if isinstance(state, basestring):
      self.value = self._name_map[state]
    elif isinstance(state, self.__class__):
      self.value = state.value
    else:
      self.value = state

  def __repr__(self):
    return self._value_map[self.value]

  def __hash__(self):
    return self.value

  def __eq__(self, other):
    if isinstance(other, basestring):
      return self.value == self._name_map[other]
    elif isinstance(other, self.__class__):
      return self.value == other.value
    else:
      return self.value == other

  def __ne__(self, other):
    return not self.__eq__(other)

  def CName(self):
    return self._c_value_map[self.value]

  @classmethod
  def Names(cls):
    return [ParamSourceEncoding(v) for v in cls._value_map.keys()]

  @classmethod
  def iteritems(cls):
    return cls._name_map.iteritems()

  @classmethod
  def HeaderFile(cls):
    return "avionics/firmware/params/param_source_header.h"

  @classmethod
  def TypeName(cls):
    return "ParamSourceEncoding"

ParamSourceEncoding.BZIP2 = ParamSourceEncoding(0)

class ParamSourceHeader (py_types.Structure):
  global ParamSourceEncoding
  global ParamSourceHeaderMagic
  global py_types

  _fields_ = [
      ('magic', ParamSourceHeaderMagic),
      ('encoding', ParamSourceEncoding),
      ('length', py_types.UInt32),
      ('crc', py_types.UInt32),

  ]
  _offsets_ = {
      'magic': 0,
      'encoding': 4,
      'length': 8,
      'crc': 12,

  }
  size = 16
  alignment = 4


