// This file is automatically generated.  Do not edit.
#ifndef AVIONICS_FIRMWARE_SERIAL_BATT_SERIAL_PARAMS_H_
#define AVIONICS_FIRMWARE_SERIAL_BATT_SERIAL_PARAMS_H_

#include <stdint.h>

#include "avionics/firmware/serial/serial_params.h"
typedef enum {
  kBattHardwareForceSigned = -1,
  kBattHardwareSmallCell15V1 = 0,
  kBattHardwareBigCell18V1 = 1,
  kBattHardwareSmallCell15Aa = 2,
  kBattHardwareBigCell18Aa = 3,
  kBattHardwareSmallCell15Ab = 4,
  kBattHardwareBigCell18Ab = 5,
  kBattHardwareSmallCell17Ab = 6,
  kBattHardwareSmallCell15Ac = 7,
  kBattHardwareBigCell18Ac = 8,
  kBattHardwareSmallCell17Ac = 9,
  kBattHardwareSmallCell17Ad = 10,
  kNumBattHardwares = 11,
  kBattHardwareForceSize = 0x7fffffff,
} __attribute__((packed)) BattHardware;

typedef struct {
  char serial_number[32];
  char part_name[32];
  char part_number[32];
  BattHardware hardware_revision;
  uint32_t date_of_manufacture;
} BattSerialParams;

#ifdef PACK2_FLASH_POINTERS
extern const BattSerialParams *kBattSerialParams;
#endif
static const uint32_t kBattSerialParamsCrc = 0x5fc1a0a4;
static inline uint32_t BattSerialParamsGetTypeVersion(void) {
    return kBattSerialParamsCrc;
}

#endif  // AVIONICS_FIRMWARE_SERIAL_BATT_SERIAL_PARAMS_H_
