// This file is automatically generated.  Do not edit.
#ifndef AVIONICS_FIRMWARE_SERIAL_CS_SERIAL_PARAMS_H_
#define AVIONICS_FIRMWARE_SERIAL_CS_SERIAL_PARAMS_H_

#include <stdint.h>

#include "avionics/firmware/serial/serial_params.h"
typedef enum {
  kCsHardwareForceSigned = -1,
  kCsHardwareRevAa = 0,
  kCsHardwareRevAb = 1,
  kCsHardwareRevAc = 2,
  kCsHardwareRevAdClk8 = 3,
  kCsHardwareRevAdClk16 = 4,
  kNumCsHardwares = 5,
  kCsHardwareForceSize = 0x7fffffff,
} __attribute__((packed)) CsHardware;

typedef struct {
  char serial_number[32];
  char part_name[32];
  char part_number[32];
  CsHardware hardware_revision;
  uint32_t date_of_manufacture;
} CsSerialParams;

#ifdef PACK2_FLASH_POINTERS
extern const CsSerialParams *kCsSerialParams;
#endif
static const uint32_t kCsSerialParamsCrc = 0x5fc1a0a4;
static inline uint32_t CsSerialParamsGetTypeVersion(void) {
    return kCsSerialParamsCrc;
}

#endif  // AVIONICS_FIRMWARE_SERIAL_CS_SERIAL_PARAMS_H_
