// This file is automatically generated.  Do not edit.
#ifndef AVIONICS_FIRMWARE_SERIAL_FC_SERIAL_PARAMS_H_
#define AVIONICS_FIRMWARE_SERIAL_FC_SERIAL_PARAMS_H_

#include <stdint.h>

#include "avionics/firmware/serial/serial_params.h"
typedef enum {
  kFcHardwareForceSigned = -1,
  kFcHardwareRevAb = 0,
  kFcHardwareRevBa = 1,
  kFcHardwareRevBb = 2,
  kFcHardwareRevBc = 3,
  kFcHardwareRevBd = 4,
  kNumFcHardwares = 5,
  kFcHardwareForceSize = 0x7fffffff,
} __attribute__((packed)) FcHardware;

typedef struct {
  char serial_number[32];
  char part_name[32];
  char part_number[32];
  FcHardware hardware_revision;
  uint32_t date_of_manufacture;
} FcSerialParams;

#ifdef PACK2_FLASH_POINTERS
extern const FcSerialParams *kFcSerialParams;
#endif
static const uint32_t kFcSerialParamsCrc = 0x5fc1a0a4;
static inline uint32_t FcSerialParamsGetTypeVersion(void) {
    return kFcSerialParamsCrc;
}

#endif  // AVIONICS_FIRMWARE_SERIAL_FC_SERIAL_PARAMS_H_
