// This file is automatically generated.  Do not edit.
#ifndef AVIONICS_FIRMWARE_SERIAL_GROUND_IO_SERIAL_PARAMS_H_
#define AVIONICS_FIRMWARE_SERIAL_GROUND_IO_SERIAL_PARAMS_H_

#include <stdint.h>

#include "avionics/firmware/serial/serial_params.h"
typedef enum {
  kGroundIoHardwareForceSigned = -1,
  kGroundIoHardwareRevAa = 1,
  kGroundIoHardwareForceSize = 0x7fffffff,
} __attribute__((packed)) GroundIoHardware;

typedef struct {
  char serial_number[32];
  char part_name[32];
  char part_number[32];
  GroundIoHardware hardware_revision;
  uint32_t date_of_manufacture;
} GroundIoSerialParams;

#ifdef PACK2_FLASH_POINTERS
extern const GroundIoSerialParams *kGroundIoSerialParams;
#endif
static const uint32_t kGroundIoSerialParamsCrc = 0x5fc1a0a4;
static inline uint32_t GroundIoSerialParamsGetTypeVersion(void) {
    return kGroundIoSerialParamsCrc;
}

#endif  // AVIONICS_FIRMWARE_SERIAL_GROUND_IO_SERIAL_PARAMS_H_
