// This file is automatically generated.  Do not edit.
#ifndef AVIONICS_FIRMWARE_SERIAL_MOTOR_SERIAL_PARAMS_H_
#define AVIONICS_FIRMWARE_SERIAL_MOTOR_SERIAL_PARAMS_H_

#include <stdint.h>

#include "avionics/firmware/serial/serial_params.h"
typedef enum {
  kMotorHardwareForceSigned = -1,
  kMotorHardwareGinA1 = 0,
  kMotorHardwareGinA2 = 1,
  kMotorHardwareGinA3 = 2,
  kMotorHardwareGinA4Clk16 = 3,
  kMotorHardwareGinA4Clk8 = 4,
  kMotorHardwareOzoneA1 = 5,
  kNumMotorHardwares = 6,
  kMotorHardwareForceSize = 0x7fffffff,
} __attribute__((packed)) MotorHardware;

typedef struct {
  char serial_number[32];
  char part_name[32];
  char part_number[32];
  MotorHardware hardware_revision;
  uint32_t date_of_manufacture;
} MotorSerialParams;

#ifdef PACK2_FLASH_POINTERS
extern const MotorSerialParams *kMotorSerialParams;
#endif
static const uint32_t kMotorSerialParamsCrc = 0x5fc1a0a4;
static inline uint32_t MotorSerialParamsGetTypeVersion(void) {
    return kMotorSerialParamsCrc;
}

#endif  // AVIONICS_FIRMWARE_SERIAL_MOTOR_SERIAL_PARAMS_H_
