// This file is automatically generated.  Do not edit.
#ifndef AVIONICS_FIRMWARE_SERIAL_RECORDER_SERIAL_PARAMS_H_
#define AVIONICS_FIRMWARE_SERIAL_RECORDER_SERIAL_PARAMS_H_

#include <stdint.h>

#include "avionics/firmware/serial/serial_params.h"
typedef enum {
  kRecorderHardwareForceSigned = -1,
  kRecorderHardwareRevAa = 0,
  kRecorderHardwareRevBa = 1,
  kNumRecorderHardwares = 2,
  kRecorderHardwareForceSize = 0x7fffffff,
} __attribute__((packed)) RecorderHardware;

typedef struct {
  char serial_number[32];
  char part_name[32];
  char part_number[32];
  RecorderHardware hardware_revision;
  uint32_t date_of_manufacture;
} RecorderSerialParams;

#ifdef PACK2_FLASH_POINTERS
extern const RecorderSerialParams *kRecorderSerialParams;
#endif
static const uint32_t kRecorderSerialParamsCrc = 0x5fc1a0a4;
static inline uint32_t RecorderSerialParamsGetTypeVersion(void) {
    return kRecorderSerialParamsCrc;
}

#endif  // AVIONICS_FIRMWARE_SERIAL_RECORDER_SERIAL_PARAMS_H_
