// This file is automatically generated.  Do not edit.
#ifndef AVIONICS_FIRMWARE_SERIAL_SERVO_SERIAL_PARAMS_H_
#define AVIONICS_FIRMWARE_SERIAL_SERVO_SERIAL_PARAMS_H_

#include <stdint.h>

#include "avionics/firmware/serial/serial_params.h"
typedef enum {
  kServoHardwareForceSigned = -1,
  kServoHardwareRevAa = 0,
  kServoHardwareRevBa = 1,
  kServoHardwareRevBb = 2,
  kServoHardwareRevBc = 3,
  kNumServoHardwares = 4,
  kServoHardwareForceSize = 0x7fffffff,
} __attribute__((packed)) ServoHardware;

typedef struct {
  char serial_number[32];
  char part_name[32];
  char part_number[32];
  ServoHardware hardware_revision;
  uint32_t date_of_manufacture;
} ServoSerialParams;

#ifdef PACK2_FLASH_POINTERS
extern const ServoSerialParams *kServoSerialParams;
#endif
static const uint32_t kServoSerialParamsCrc = 0x5fc1a0a4;
static inline uint32_t ServoSerialParamsGetTypeVersion(void) {
    return kServoSerialParamsCrc;
}

#endif  // AVIONICS_FIRMWARE_SERIAL_SERVO_SERIAL_PARAMS_H_
