// This file is automatically generated.  Do not edit.
#ifndef AVIONICS_FIRMWARE_SERIAL_SHORT_STACK_SERIAL_PARAMS_H_
#define AVIONICS_FIRMWARE_SERIAL_SHORT_STACK_SERIAL_PARAMS_H_

#include <stdint.h>

#include "avionics/firmware/serial/serial_params.h"
typedef enum {
  kShortStackHardwareForceSigned = -1,
  kShortStackHardwareRev01 = 0,
  kNumShortStackHardwares = 1,
  kShortStackHardwareForceSize = 0x7fffffff,
} __attribute__((packed)) ShortStackHardware;

typedef struct {
  char serial_number[32];
  char part_name[32];
  char part_number[32];
  ShortStackHardware hardware_revision;
  uint32_t date_of_manufacture;
} ShortStackSerialParams;

#ifdef PACK2_FLASH_POINTERS
extern const ShortStackSerialParams *kShortStackSerialParams;
#endif
static const uint32_t kShortStackSerialParamsCrc = 0x5fc1a0a4;
static inline uint32_t ShortStackSerialParamsGetTypeVersion(void) {
    return kShortStackSerialParamsCrc;
}

#endif  // AVIONICS_FIRMWARE_SERIAL_SHORT_STACK_SERIAL_PARAMS_H_
