// This file is automatically generated.  Do not edit.
#ifndef AVIONICS_COMMON_GPS_RECEIVER_H_
#define AVIONICS_COMMON_GPS_RECEIVER_H_

#include <stdint.h>

typedef enum {
  kGpsReceiverTypeForceSigned = -1,
  kGpsReceiverTypeNone = 0,
  kGpsReceiverTypeNovAtel = 1,
  kGpsReceiverTypeSeptentrio = 2,
  kNumGpsReceiverTypes = 3,
  kGpsReceiverTypeForceSize = 0x7fffffff,
} __attribute__((packed)) GpsReceiverType;

#endif  // AVIONICS_COMMON_GPS_RECEIVER_H_
