#ifndef AVIONICS_NETWORK_WINCH_MESSAGE_TYPE_H_
#define AVIONICS_NETWORK_WINCH_MESSAGE_TYPE_H_

// Generated by generate_message_type.py; do not edit.

#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  kWinchMessageTypePlcWinchCommand = 1,
  kWinchMessageTypePlcWinchSetState = 3,
  kWinchMessageTypePlcWinchStatus = 2,
  kNumWinchMessageTypes = 4
} WinchMessageType;

const char *WinchMessageTypeToString(WinchMessageType message_type);
const char *WinchMessageTypeToShortString(WinchMessageType message_type);
bool IsValidWinchMessageType(WinchMessageType message_type);
WinchMessageType StringToWinchMessageType(const char *message_type);

#ifdef __cplusplus
}  // extern "C"
#endif

#endif  // AVIONICS_NETWORK_WINCH_MESSAGE_TYPE_H_
